# Docker CLI documented commands

# check version: docker --version
# output: Docker version 28.0.4, build b8034c0

# search docker: docker search nginx
# output: List of name, description, stars and if its official or not

# docker run explanation: docker run -d -p 80:80 docker/m347-container
